### ISSUE TITLE
\n break version 0.0.2 

### ISSUE THREAD

**Issue by jonasfj** [freethenation/durable-json-lint#3]
tried upgrading to version 0.0.2, but `require('durable-json-lint')('{"test": \n {}}')` doesn't work...

I think whitespace in human written JSON is to be expected :)

**Comment by revelt** [comment]
Yeah, it's happening, confirmed. I thought I can bypass `fs.readJsonSync`, read UTF-8 string instead and run it through this library. However, incoming string does have `\n`.

**Comment by richardklafter** [comment]
The issue should be fixed. I will push the module to NPM soon.

**Comment by revelt** [comment]
That's exciting! Looking forward to tap it 👍👍 🍺🍺 👍

**Comment by LegNeato** [comment]
Any update on when this will be pushed to npm?

**Comment by DanielSWolf** [comment]
Still not fixed. The exact error I get is this:

```
{ errors:
   [ { Error: Line 1: Unexpected token ILLEGAL
         at throwError (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1161:21)
         at advance (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1089:9)
         at lookahead (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1118:18)
         at match (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1239:21)
         at parseObjectInitialiser (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1440:17)
         at parsePrimaryExpression (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1548:20)
         at /Users/wolf/dev/json-test/node_modules/esprima/esprima.js:3596:38
         at trackLeftHandSideExpressionAllowCall (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:3491:61)
         at parsePostfixExpression (/Users/wolf/dev/json-test/node_modules/esprima/esprima.js:1695:20)
         at /Users/wolf/dev/json-test/node_modules/esprima/esprima.js:3596:38 index: 21, lineNumber: 1, column: 22, status: 'crash' } ],
  json: null }
```

This issue has been open for almost five months now. Seems to me the project is dead. 😞

**Comment by revelt** [comment]
I'm seriously thinking about creating my own JSON fixer. Basically, my brewing idea is I'd first treat the input as string, assume nothing, never parse, only scrutinise. If anything fixable is detected, it would fix that, but whatever the outcome, the output is returned string. Worst case scenario then, is fixer would nothing, as opposed to `throw` messages like @DanielSWolf mentioned above.

There's a huge need and market for dirty JSON fixer.

**Comment by freethenation** [comment]
pushed to npm
